name: "Создание задачи"
description: "Шаблон для создания новой задачи"
title: "[ISSUE_TYPE]-<номер>: <краткое описание>"
labels: []
assignees: []
body:
  - type: input
    id: issue_type
    attributes:
      label: "Тип задачи"
      description: "Например, Bug, Feature, Improvement"
      placeholder: "Feature"
    validations:
      required: true

  - type: input
    id: issue_number
    attributes:
      label: "Номер задачи"
      description: "Оставьте пустым, если номер генерируется автоматически"
      placeholder: "123"
  
  - type: input
    id: summary
    attributes:
      label: "Краткое описание"
      description: "Одной строкой, что нужно сделать"
      placeholder: "Добавить авторизацию через OAuth2"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: "Подробное описание"
      description: "Опишите задачу подробнее"
      placeholder: "Описание функционала, шаги реализации, контекст"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "Приоритет"
      description: "P0 – критично, P1 – важно, P2 – желательно"
      options:
        - "P0 (Критичный)"
        - "P1 (Высокий)"
        - "P2 (Средний)"
    validations:
      required: true

  - type: input
    id: deadline
    attributes:
      label: "Дедлайн"
      description: "Дата завершения в формате YYYY-MM-DD"
      placeholder: "2025-03-10"
