name: Шаблон для создания новой задачи
body:
  - type: dropdown
    id: case
    attributes:
      label: "Выберите кейс"
      options:
        - "Validator"
        - "Worker"
        - "Web"
        - "Bot"
        - "Обновление панели"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Описание задачи"
      description: "Подробно опишите, что нужно сделать"
      placeholder: "Описание с деталями реализации, картинки, ссылки на другие задачи"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "Приоритет"
      description: "Выберите уровень важности"
      options:
        - "P0 - Срочно"
        - "P1 - Средне"
        - "P2 - Терпит"
        - "Нет устанавливать"
    validations:
      required: true

  - type: input
    id: deadline
    attributes:
      label: "Дедлайн"
      description: "Крайний срок выполнения (формат: ГГГГ-ММ-ДД)"
      placeholder: "2025-03-15"
    validations:
      required: false
