name: "Новая задача"
description: "Шаблон для создания задачи"
labels: ["task"]
body:
  - type: input
    id: title
    attributes:
      label: "Краткое описание задачи"
      description: "Опишите суть задачи в одном предложении"
      placeholder: "Добавить поддержку нового API"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Подробное описание"
      description: "Опишите задачу подробнее, включая необходимую информацию, требования и ожидаемый результат"
      placeholder: "Опишите, что должно быть сделано и почему"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Шаги выполнения"
      description: "Разбейте задачу на конкретные шаги, если возможно"
      placeholder: "1. Подготовить API\n2. Написать код\n3. Покрыть тестами"
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: "Приоритет"
      description: "Выберите уровень важности задачи"
      options:
        - "Низкий"
        - "Средний"
        - "Высокий"
    validations:
      required: true

  - type: input
    id: deadline
    attributes:
      label: "Дедлайн (если есть)"
      description: "Укажите срок выполнения задачи"
      placeholder: "2025-03-10"
    validations:
      required: false
